# This is a basic workflow to help you get started with Actions

name: test

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: "arn:aws:iam::339712835459:role/terraform_practice_repo_admin_role"
          role-session-name: "test-session"
          aws-region: "us-east-1"

      # Runs a single command using the runners shell
      - name: check aws identity
        run: aws sts get-caller-identity

      - name: run terraform code
        working-directory: practice_eks/
        run: |
          terraform init -backend-config="bucket=remote-terraform-backend-oleksandr""
          terraform apply -auto-approve -input=false -var-file=dev.tfvars

