# This is a basic workflow to help you get started with Actions

name: test

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

# Controls when the workflow will run
on:
  push:
    branches: # list of all branches that will trigger the workflow
      - main
      - test
      - development 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# workflow scope variable
env:
  ENVIRONMENT_SETUP: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/test' && 'test') || 'development' }} 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  infra-deploy:

    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || (github.ref == 'refs/heads/test' && 'test') || 'development' }}  # for test purpuces: when merging to main use dev environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: practice_eks/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          role-session-name: "test-session"
          aws-region: "us-east-1"

      # Runs a single command using the runners shell
      - name: check aws identity
        run: aws sts get-caller-identity

      - name: initialize tf repo and set up remote backend
        run: |
          terraform init -backend-config="bucket=${{ vars.BACKEND_BUCKET }}"

      - name: run format check
        run: terraform fmt -check

      - name: run tf validatiion
        run: terraform validate

      - name: run terraform plan
        run: terraform plan -var-file="${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'development' }}.tfvars" 

      - name: apply terraform plan
        run: terraform apply -auto-approve -input=false -var-file="${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'development' }}.tfvars" 

      #- name: apply terraform plan 
        #run: terraform destroy -auto-approve -var-file="${{ (github.ref == 'refs/heads/main' && 'prod') || (github.ref == 'refs/heads/test' && 'test') || 'development' }}.tfvars" 